name: Test

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  test-versions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        eslint-version: [7, 8, 9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Test
        run: |
          cd examples/eslint${{ matrix.eslint-version }}
          npm ci
          npm run lint
